### ISSUE TITLE
Outdated :latest image?

### ISSUE THREAD

**Issue by mikea** [krallin/tini-images#2]
Current ubuntu:latest is xenial. It seems that tini-images is not built for xenial at all. Could you update the images please?

**Comment by krallin** [comment]
Hey there @mikea. Thanks for the heads up, yes I should indeed do so. I'm working on this now 😄  (should be out soon, but this uses a bit of Python to run tests, and PyPi happens to be down right now, so I'll have to wait for a little bit)

**Comment by krallin** [comment]
The new images are building now! You can follow the progress here: https://hub.docker.com/r/krallin/ubuntu-tini/builds/

The tags for Xenial will be `16.04` and `xenial` (`latest` will point to Xenial as well, but of course I encourage you to avoid `latest` since it'll change over time).

Thanks for the heads up here!

Cheers,
